### ISSUE TITLE
How do I switch between output formats?

### ISSUE THREAD

**Issue by jhult** [oysteing/jira-mailqueue#1]
By default, the app outputs XML. If I want JSON instead, how do I request this?

**Comment by oysteing** [comment]
The trick is to add the corresponding HTTP header. You'll find a good description. Essentially, you'll need `Accept: application/json`. You can see this by doing `http -v -j https://jira.example.org/rest/mailqueue/1.0/status`, just replace jira.example.org with your server.

Good luck!
